---
- name: Include packages variables
  include_vars: packages.yml

- name: Install default and extra packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ common_default_packages }} + {{ common_extra_packages|default([]) }}"
