---
- hosts: all
  become: true

  vars:
    - ansible_python_interpreter: "/usr/bin/python3"

  roles:
    - {role: common, tags: common}
    - {role: docker, tags: docker}
    - {role: node-exporter, tags: node-exporter}
