---
- hosts: localhost
  become: false

  vars:
    project:  "{{ lookup('env','PROJECT') }}"

  tasks:
    - name: "Create invetory file"
      template:
        src: "/uma-automator/ansible/templates/{{ item }}.j2"
        dest: "/uma-automator/ansible/{{ item }}"
        force: false
      with_items:
        - inventory.gcp.yml
